### ISSUE TITLE
Web methods CI with Azure DevOps - build failing

### ISSUE THREAD

**Issue by aksh-h** [SoftwareAG/sagdevops-ci-assets#5]
I'm trying to find a way to implement work flow using Azure DevOps.
Can anyone help on web methods CI/CD with azure DevOps?

**Comment by aksh-h** [comment]
Hi there, 

Configured the build as given in the document, but build is failing often. Anything need to be taken care before configuring this demo set up?
Please let me know.
Here is the error message.
```
generate-composites:
     [java] java.lang.ExceptionInInitializerError
     [java] 	at com.ibm.icu.impl.ICUResourceBundle.<clinit>(ICUResourceBundle.java:464)
     [java] 	at com.ibm.icu.util.ULocale.getAvailableLocales(ULocale.java:993)
     [java] 	at com.softwareag.g11n.util.iContext.<clinit>(iContext.java:216)
     [java] 	at com.wm.lang.ns.NSService.init(NSService.java:168)
     [java] 	at com.wm.lang.ns.NSService.<init>(NSService.java:145)
     [java] 	at com.wm.app.b2b.server.BaseService.<init>(BaseService.java:172)
     [java] 	at com.wm.app.b2b.server.FlowSvcImpl.<init>(FlowSvcImpl.java:47)
     [java] 	at com.wm.app.b2b.server.FlowServiceFactory.createFromNodeDef(FlowServiceFactory.java:22)
     [java] 	at com.wm.app.b2b.server.PackageManager.createNode(PackageManager.java:2571)
     [java] 	at com.wm.app.b2b.server.PackageManager.getNode(PackageManager.java:1587)
     [java] 	at com.wm.app.b2b.server.PackageManager.getFileSystemNodes(PackageManager.java:1564)
     [java] 	at com.wm.app.b2b.server.PackageManager.loadServices(PackageManager.java:1080)
     [java] 	at com.wm.app.b2b.server.PackageManager.loadServices(PackageManager.java:1047)
     [java] 	at com.wm.app.b2b.server.PackageManager.processPackageManifest(PackageManager.java:1004)
     [java] 	at com.wm.app.b2b.server.PackageManager.loadPackage(PackageManager.java:788)
     [java] 	at com.wm.app.b2b.server.PackageManager.loadPackage(PackageManager.java:669)
     [java] 	at com.wm.app.b2b.server.PackageManager.loadPackage(PackageManager.java:431)
     [java] 	at com.wm.app.b2b.server.packageLoader.SerialPackageLoader.loadPackages(SerialPackageLoader.java:275)
     [java] 	at com.wm.app.b2b.server.PackageManager.loadPackages(PackageManager.java:404)
     [java] 	at com.wm.app.b2b.server.PackageManager.init(PackageManager.java:325)
     [java] 	at com.wm.app.b2b.server.PackageManager.init(PackageManager.java:195)
     [java] 	at com.wm.app.b2b.server.deployer.SolutionAssembler.exportDesignTimeAssets(SolutionAssembler.java:128)
     [java] 	at com.wm.app.b2b.server.deployer.SolutionAssembler.export(SolutionAssembler.java:304)
     [java] 	at com.wm.app.b2b.server.deployer.SolutionAssembler.main(SolutionAssembler.java:410)
     [java] Caused by: java.lang.IllegalArgumentException: Invalid version number: Version number may be negative or greater than 255
     [java] 	at com.ibm.icu.util.VersionInfo.getInstance(VersionInfo.java:191)
     [java] 	at com.ibm.icu.impl.ICUDebug.getInstanceLenient(ICUDebug.java:65)
     [java] 	at com.ibm.icu.impl.ICUDebug.<clinit>(ICUDebug.java:69)
     [java] 	... 24 more
     [java] Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class com.ibm.icu.impl.ICUDebug
     [java] 	at com.ibm.icu.impl.NormalizerDataReader.<clinit>(NormalizerDataReader.java:300)
     [java] 	at com.ibm.icu.impl.NormalizerImpl.<init>(NormalizerImpl.java:288)
     [java] 	at com.ibm.icu.impl.NormalizerImpl.<clinit>(NormalizerImpl.java:35)
     [java] 	at com.ibm.icu.text.Normalizer.compose(Normalizer.java:873)
     [java] 	at com.ibm.icu.text.Normalizer$NFKCMode.normalize(Normalizer.java:469)
     [java] 	at com.ibm.icu.text.Normalizer.normalize(Normalizer.java:1111)
     [java] 	at com.wm.util.text.IBMNormalizer.normalize(IBMNormalizer.java:32)
     [java] 	at com.wm.util.text.IBMNormalizer.normalize(IBMNormalizer.java:21)
     [java] 	at com.wm.util.EncUtil.normalize(EncUtil.java:766)
     [java] 	at com.wm.app.b2b.server.deployer.processors.DesignTimeAssetsDeployerImpl.createManifestEntries(DesignTimeAssetsDeployerImpl.java:211)
     [java] 	at com.wm.app.b2b.server.deployer.processors.DesignTimeAssetsDeployerImpl.createManifestEntries(DesignTimeAssetsDeployerImpl.java:124)
     [java] 	at com.wm.app.b2b.server.deployer.SolutionAssembler.exportDesignTimeAssets(SolutionAssembler.java:170)
     [java] 	at com.wm.app.b2b.server.deployer.SolutionAssembler.export(SolutionAssembler.java:304)
     [java] 	at com.wm.app.b2b.server.deployer.SolutionAssembler.main(SolutionAssembler.java:410)

BUILD FAILED
C:\Program Files (x86)\Jenkins\workspace\wm-ci\build.xml:27: The following error occurred while executing this line:
C:\Tools\SampleWebMethodsCode\SAG-Git-Clone\sagdevops-ci-assets\buildCallABE.xml:25: The following error occurred while executing this line:
C:\SoftwareAG_1\common\AssetBuildEnvironment\master_build\build.xml:377: The following error occurred while executing this line:
C:\SoftwareAG_1\common\AssetBuildEnvironment\master_build\build.xml:99: The following error occurred while executing this line:
C:\SoftwareAG_1\common\AssetBuildEnvironment\IS\build.xml:116: The following error occurred while executing this line:
C:\SoftwareAG_1\common\AssetBuildEnvironment\IS\build.xml:144: The following error occurred while executing this line:
C:\SoftwareAG_1\common\AssetBuildEnvironment\IS\build.xml:169: The following error occurred while executing this line:
C:\SoftwareAG_1\common\AssetBuildEnvironment\IS\build.xml:189: Java returned: 1

Total time: 5 seconds```
